//! The server-owned template merge engine: an exact behavioural twin of the
//! 3-way merge that `@shadowcat/core` computes client-side (`merge3`,
//! `computePull`, `computeRevert`, `planToUpdate`, `applyResolutions` and
//! their internal helpers). The two implementations are pinned together by
//! one conformance corpus
//! (`src/client/core/src/__fixtures__/merge-conformance.json`) GENERATED by
//! running the client engine over the case matrix; the test suite here
//! asserts byte-identical results, so a divergence fails on whichever side
//! moved. Rust ownership replaces the client's `structuredClone` discipline:
//! every cross-tree value is cloned at the crossing point the client comments
//! mark, which the corpus's aliasing-sensitive cases pin behaviourally.
//!
//! # Accepted divergences from the client engine
//!
//! Three differences are accepted as dead or cosmetic; none can change a
//! merge RESULT:
//!
//! - **Key sorting is UTF-8 byte order** (Rust `String` `Ord`, via the
//!   `BTreeSet` traversals in `tree::structural_diff_at`,
//!   `embedded::merge3_embedded`/`embedded::revert_embedded` and
//!   `plan::plan_to_update`) where the client sorts UTF-16 code units. Merge
//!   results are order-independent by design; only diff/conflict/change ORDER
//!   within a result can differ, and only on keys mixing U+E000–U+FFFF with
//!   astral-plane characters.
//! - **`tree::get_pointer`/`tree::delete_pointer` reject non-canonical
//!   array-index tokens** (`"01"`, `"+1"`, …) that the client would coerce
//!   via `Number(tok)`. Merge-generated pointers only ever carry canonical
//!   indices (`structural_diff` and `prefix_conflicts` format `usize`
//!   values), so the coercing path is unreachable here.
//! - **Base correlation stringifies `Uuid` canonically** where the client
//!   compared verbatim strings (`embedded::merge3_embedded`'s
//!   `base_by_source` keys). A non-canonical legacy `sourceId` (uppercase
//!   hex, braces, …) correlates as instance-added — the keep direction,
//!   never the drop direction.

#![deny(missing_docs)]
#![deny(clippy::missing_docs_in_private_items)]

/// `MergeBase`/`MergeBands`, the snapshot builders and the placement
/// exclusion set.
pub mod bands;
/// Embedded-collection merge/revert and subtree restamping.
pub(crate) mod embedded;
/// `merge3`, the pull/revert computations, and update-plan emission.
pub mod plan;
/// Single-tree diff/merge primitives and JSON-pointer helpers.
pub(crate) mod tree;
/// The per-document visibility oracle the merge consults by identity.
pub mod visibility;

#[cfg(test)]
mod tests;

use serde::{Deserialize, Serialize};
use serde_json::Value;
use ts_rs::TS;

pub use bands::{
    is_placement_excluded, placement_exclusions, snapshot_base, EmbeddedBaseChild, MergeBands,
    MergeBase,
};
pub use plan::{
    apply_resolutions, compute_pull, compute_revert, merge3, plan_to_update, MergePlan,
};
pub use visibility::{AllVisible, MergeVisibility, RequesterView, Side};

/// A merge computation that refused to run. Wire-level errors (missing
/// documents, authorization, stale resolutions) live in the protocol layer,
/// not here.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MergeError {
    /// The child's stored `base` snapshot is present but does not parse as a
    /// `MergeBase`. A corrupt snapshot cannot carry correlation information
    /// the merge could trust, and falling back to a clean template-wins
    /// merge would silently destroy child-local edits — so the pull fails
    /// closed and nothing is written. Carries no user data: the offending
    /// document is identified by the caller's context.
    CorruptBase,
    /// The `MergeVisibility` oracle could not answer what the requester may
    /// see of a document (an override pointer the redaction classifier cannot
    /// place). The merge discloses nothing and writes nothing.
    VisibilityUnknown,
}

impl std::fmt::Display for MergeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MergeError::CorruptBase => {
                f.write_str("the stored merge base does not parse as a MergeBase snapshot")
            }
            MergeError::VisibilityUnknown => {
                f.write_str("the requester's view of a merged document could not be resolved")
            }
        }
    }
}

impl std::error::Error for MergeError {}

/// How `take_template` resolves a conflict: `"set"` writes the parent value,
/// `"delete"` removes the key. Mirrors the client `Conflict.parentKind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../types/generated/")]
#[serde(rename_all = "snake_case")]
pub enum ParentKind {
    /// Write the parent/template value at the conflict path.
    Set,
    /// Remove the key at the conflict path.
    Delete,
}

/// A field changed on both the template (parent) and instance (child) sides
/// since the last sync. `base`/`parent`/`child` are ABSENT (not `null`) when
/// that side has no value at `path` — the parent's side deleted it, the
/// child's side deleted it, or neither side's snapshot contained it — matching
/// the client engine's `undefined` semantics under JSON serialization.
/// Mirrors the client `Conflict` type.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../types/generated/")]
#[serde(rename_all = "camelCase")]
pub struct MergeConflict {
    /// The RFC-6901 pointer of the conflicting field.
    pub path: String,
    /// The value at `path` in the last-synced snapshot both sides diverged
    /// from; absent when the snapshot has no value there.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "unknown")]
    pub base: Option<Value>,
    /// The template/parent side's current value at `path`; absent iff the
    /// parent deleted it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "unknown")]
    pub parent: Option<Value>,
    /// The instance/child side's current value at `path`; absent iff the
    /// child deleted it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "unknown")]
    pub child: Option<Value>,
    /// How `take_template` resolves this conflict: `Set` writes `parent`,
    /// `Delete` removes the key.
    pub parent_kind: ParentKind,
}
