//! The server-owned template merge engine: an exact behavioural twin of the
//! 3-way merge that `@shadowcat/core` computes client-side (`merge3`,
//! `computePull`, `computeRevert`, `planToUpdate`, `applyResolutions` and
//! their internal helpers). The two implementations are pinned together by
//! one conformance corpus
//! (`src/client/core/src/__fixtures__/merge-conformance.json`) GENERATED by
//! running the client engine over the case matrix; the test suite here
//! asserts byte-identical results, so a divergence fails on whichever side
//! moved. Rust ownership replaces the client's `structuredClone` discipline:
//! every cross-tree value is cloned at the crossing point the client comments
//! mark, which the corpus's aliasing-sensitive cases pin behaviourally.

#![deny(missing_docs)]
#![deny(clippy::missing_docs_in_private_items)]

/// `MergeBase`/`MergeBands`, the snapshot builders and the placement
/// exclusion set.
pub mod bands;
/// Embedded-collection merge/revert and subtree restamping.
pub(crate) mod embedded;
/// `merge3`, the pull/revert computations, and update-plan emission.
pub mod plan;
/// Single-tree diff/merge primitives and JSON-pointer helpers.
pub(crate) mod tree;

#[cfg(test)]
mod tests;

use serde::{Deserialize, Serialize};
use serde_json::Value;
use ts_rs::TS;

pub use bands::{
    is_placement_excluded, placement_exclusions, snapshot_base, EmbeddedBaseChild, MergeBands,
    MergeBase,
};
pub use plan::{
    apply_resolutions, compute_pull, compute_revert, merge3, plan_to_update, MergePlan,
};

/// How `take_template` resolves a conflict: `"set"` writes the parent value,
/// `"delete"` removes the key. Mirrors the client `Conflict.parentKind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../types/generated/")]
#[serde(rename_all = "snake_case")]
pub enum ParentKind {
    /// Write the parent/template value at the conflict path.
    Set,
    /// Remove the key at the conflict path.
    Delete,
}

/// A field changed on both the template (parent) and instance (child) sides
/// since the last sync. `base`/`parent`/`child` are ABSENT (not `null`) when
/// that side has no value at `path` — the parent's side deleted it, the
/// child's side deleted it, or neither side's snapshot contained it — matching
/// the client engine's `undefined` semantics under JSON serialization.
/// Mirrors the client `Conflict` type.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../types/generated/")]
#[serde(rename_all = "camelCase")]
pub struct MergeConflict {
    /// The RFC-6901 pointer of the conflicting field.
    pub path: String,
    /// The value at `path` in the last-synced snapshot both sides diverged
    /// from; absent when the snapshot has no value there.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "unknown")]
    pub base: Option<Value>,
    /// The template/parent side's current value at `path`; absent iff the
    /// parent deleted it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "unknown")]
    pub parent: Option<Value>,
    /// The instance/child side's current value at `path`; absent iff the
    /// child deleted it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "unknown")]
    pub child: Option<Value>,
    /// How `take_template` resolves this conflict: `Set` writes `parent`,
    /// `Delete` removes the key.
    pub parent_kind: ParentKind,
}
